from enum import IntEnum

KeyboardPageId = 0x07
KeypadPageId   = 0x07

class KeyboardPage(IntEnum):
    Undefined                               = 0x00
    KeyboardErrorRollOver                   = 0x01
    KeyboardPOSTFail                        = 0x02
    KeyboardErrorUndefined                  = 0x03
    Keyboard_a_and_A                        = 0x04 # a and A
    Keyboard_b_and_B                        = 0x05
    Keyboard_c_and_C                        = 0x06
    Keyboard_d_and_D                        = 0x07
    Keyboard_e_and_E                        = 0x08
    Keyboard_f_and_F                        = 0x09
    Keyboard_g_and_G                        = 0x0A
    Keyboard_h_and_H                        = 0x0B
    Keyboard_i_and_I                        = 0x0C
    Keyboard_j_and_J                        = 0x0D
    Keyboard_k_and_K                        = 0x0E
    Keyboard_l_and_L                        = 0x0F
    Keyboard_m_and_M                        = 0x10
    Keyboard_n_and_N                        = 0x11
    Keyboard_o_and_O                        = 0x12
    Keyboard_p_and_P                        = 0x13
    Keyboard_q_and_Q                        = 0x14
    Keyboard_r_and_R                        = 0x15
    Keyboard_s_and_S                        = 0x16
    Keyboard_t_and_T                        = 0x17
    Keyboard_u_and_U                        = 0x18
    Keyboard_v_and_V                        = 0x19
    Keyboard_w_and_W                        = 0x1A
    Keyboard_x_and_X                        = 0x1B
    Keyboard_y_and_Y                        = 0x1C
    Keyboard_z_and_Z                        = 0x1D
    Keyboard_1_and_Bang                     = 0x1E # 1 and !
    Keyboard_2_and_At                       = 0x1F # 2 and @
    Keyboard_3_and_Hash                     = 0x20 # 3 and #
    Keyboard_4_and_Dollar                   = 0x21 # 4 and $
    Keyboard_5_and_Precent                  = 0x22 # 5 and %
    Keyboard_6_and_Caret                    = 0x23 # 6 and ^
    Keyboard_7_and_Ampersand                = 0x24 # 7 and &
    Keyboard_8_and_Star                     = 0x25 # 8 and *
    Keyboard_9_and_Leftround                = 0x26 # 9 and (
    Keyboard_0_and_Rightround               = 0x27 # 0 and )
    KeyboardReturnEnter                     = 0x28 # Enter
    KeyboardESCAPE                          = 0x29
    KeyboardDelete                          = 0x2A # Backspace 退格
    KeyboardTab                             = 0x2B
    KeyboardSpacebar                        = 0x2C
    Keyboard_Minus_and_Undercore            = 0x2D # - and _
    Keyboard_Equal_and_Plus                 = 0x2E # = and +
    Keyboard_Leftsquare_and_Leftcurly       = 0x2F # [ and {
    Keyboard_Rightsquare_and_RightCurly     = 0x30 # ] and }
    Keyboard_Backslash_and_Vertbar          = 0x31 # \ and |
    Keyboard_nonUS_Hash_and_Tilde           = 0x32 # 非美国键盘的 # and ~
    Keyboard_Semic_and_Colon                = 0x33 # ; and :
    Keyboard_Singlequote_and_Doublequote    = 0x34 # ' and "
    Keyboard_Graveaccent_and_Tilde          = 0x35 # ` and ~
    Keyboard_Comma_and_Leftangle            = 0x36 # , and <
    Keyboard_Dot_and_Rightangle             = 0x37 # . and >
    Keyboard_Slash_and_Quest                = 0x38 # / and ?
    KeyboardCapsLock                        = 0x39
    KeyboardF1                              = 0x3A
    KeyboardF2                              = 0x3B
    KeyboardF3                              = 0x3C
    KeyboardF4                              = 0x3D
    KeyboardF5                              = 0x3E
    KeyboardF6                              = 0x3F
    KeyboardF7                              = 0x40
    KeyboardF8                              = 0x41
    KeyboardF9                              = 0x42
    KeyboardF10                             = 0x43
    KeyboardF11                             = 0x44
    KeyboardF12                             = 0x45
    KeyboardPrintScreen                     = 0x46
    KeyboardScrollLock                      = 0x47
    KeyboardPause                           = 0x48
    KeyboardInsert                          = 0x49
    KeyboardHome                            = 0x4A
    KeyboardPageUp                          = 0x4B
    KeyboardDeleteForword                   = 0x4C # DELETE键
    KeyboardEnd                             = 0x4D
    KeyboardPageDown                        = 0x4E
    KeyboardRightArrow                      = 0x4F # →
    KeyboardLeftArrow                       = 0x50 # ←
    KeyboardDownArrow                       = 0x51 # ↓
    KeyboardUpArrow                         = 0x52 # ↑
    
    KeypadNumLock                           = 0x53
    KeypadSlash                             = 0x54 # 数字键盘的 /
    KeypadStar                              = 0x55 # 数字键盘的 *
    KeypadMinus                             = 0x56 # 数字键盘的 -
    KeypadPlus                              = 0x57 # 数字键盘的 +
    KeypadEnter                             = 0x58 # 数字键盘的 Enter
    Keypad_1_and_End                        = 0x59 # 数字键盘的 1 and End
    Keypad_2_and_DownArrow                  = 0x5A # 数字键盘的 2 and ↓
    Keypad_3_and_PageDn                     = 0x5B # 数字键盘的 3 and PageDown
    Keypad_4_and_LeftArrow                  = 0x5C # 数字键盘的 4 and ←
    Keypad_5                                = 0x5D # 数字键盘的 5
    Keypad_6_and_RightArrow                 = 0x5E # 数字键盘的 6 and →
    Keypad_7_and_Home                       = 0x5F # 数字键盘的 7 and Home
    Keypad_8_and_UpArrow                    = 0x60 # 数字键盘的 8 and ↑
    Keypad_9_and_PageUp                     = 0x61 # 数字键盘的 9 and PageUp
    Keypad_0_and_Insert                     = 0x62 # 数字键盘的 0 and Insert
    Keypad_Dot_and_Delete                   = 0x63 # 数字键盘的 . and Delete
    
    Keyboard_nonUS_Backslash_and_Vertbar    = 0x64 # 非美国键盘的 \ and |
    KeyboardApplication                     = 0x65
    KeyboardPower                           = 0x66
    
    KeypadEqual                             = 0x67 # =

    KeyboardF13                             = 0x68
    KeyboardF14                             = 0x69
    KeyboardF15                             = 0x6A
    KeyboardF16                             = 0x6B
    KeyboardF17                             = 0x6C
    KeyboardF18                             = 0x6D
    KeyboardF19                             = 0x6E
    KeyboardF20                             = 0x6F
    KeyboardF21                             = 0x70
    KeyboardF22                             = 0x71
    KeyboardF23                             = 0x72
    KeyboardF24                             = 0x73
    KeyboardExecute                         = 0x74
    KeyboardHelp                            = 0x75
    KeyboardMenu                            = 0x76
    KeyboardSelect                          = 0x77
    KeyboardStop                            = 0x78
    KeyboardAgain                           = 0x79
    KeyboardUndo                            = 0x7A
    KeyboardCut                             = 0x7B
    KeyboardCopy                            = 0x7C
    KeyboardPaste                           = 0x7D
    KeyboardFind                            = 0x7E
    KeyboardMute                            = 0x7F
    KeyboardVolumeUp                        = 0x80
    KeyboardVolumeDown                      = 0x81
    KeyboardLockingCapsLock                 = 0x82
    KeyboardLockingNumLock                  = 0x83
    KeyboardLockingScrollLock               = 0x84

    KeypadComma                             = 0x85 # ,
    KeypadEqualSign                         = 0x86 # =

    KeyboardInternational1                  = 0x87
    KeyboardInternational2                  = 0x88
    KeyboardInternational3                  = 0x89
    KeyboardInternational4                  = 0x8A
    KeyboardInternational5                  = 0x8B
    KeyboardInternational6                  = 0x8C
    KeyboardInternational7                  = 0x8D
    KeyboardInternational8                  = 0x8E
    KeyboardInternational9                  = 0x8F
    KeyboardLANG1                           = 0x90
    KeyboardLANG2                           = 0x91
    KeyboardLANG3                           = 0x92
    KeyboardLANG4                           = 0x93
    KeyboardLANG5                           = 0x94
    KeyboardLANG6                           = 0x95
    KeyboardLANG7                           = 0x96
    KeyboardLANG8                           = 0x97
    KeyboardLANG9                           = 0x98
    KeyboardAlternateErase                  = 0x99
    KeyboardSysReq_or_Attention             = 0x9A
    KeyboardCancel                          = 0x9B
    KeyboardClear                           = 0x9C
    KeyboardPrior                           = 0x9D
    KeyboardReturn                          = 0x9E
    KeyboardSeparator                       = 0x9F
    KeyboardOut                             = 0xA0
    KeyboardOper                            = 0xA1
    KeyboardClear_or_Again                  = 0xA2
    KeyboardCrSel_or_Props                  = 0xA3
    KeyboardExSel                           = 0xA4
    __Reserved0_Begin                       = 0xA5
    __Reserved0_End                         = 0xAF
    Keypad00                                = 0xB0
    Keypad000                               = 0xB1

    ThousandsSeparator                      = 0xB2
    DecimalSeparator                        = 0xB3
    CurrencyUnit                            = 0xB4
    CurrencySubunit                         = 0xB5
    
    KeypadLeftround                         = 0xB6 # (
    KeypadRightround                        = 0xB7 # )
    KeypadLeftcurly                         = 0xB8 # {
    KeypadRightcurly                        = 0xB9 # }
    KeypadTab                               = 0xBA
    KeypadBackspace                         = 0xBB # 退格
    KeypadA                                 = 0xBC
    KeypadB                                 = 0xBD
    KeypadC                                 = 0xBE
    KeypadD                                 = 0xBF
    KeypadE                                 = 0xC0
    KeypadF                                 = 0xC1
    KeypadXOR                               = 0xC2
    KeypadCaret                             = 0xC3 # ^
    KeypadPrecent                           = 0xC4 # %
    KeypadLeftangle                         = 0xC5 # <
    KeypadRightangle                        = 0xC6 # >
    KeypadAmpersand                         = 0xC7 # &
    KeypadDoubleAmpersand                   = 0xC8 # &&
    KeypadVertbar                           = 0xC9 # |
    KeypadDoubleVertbar                     = 0xCA # ||
    KeypadColon                             = 0xCB # :
    KeypadHash                              = 0xCC # #
    KeypadSpace                             = 0xCD # ' '
    KeypadAt                                = 0xCE # @
    KeypadBang                              = 0xCF # !
    KeypadMemoryStore                       = 0xD0
    KeypadMemoryRecall                      = 0xD1
    KeypadMemoryClear                       = 0xD2
    KeypadMemoryAdd                         = 0xD3
    KeypadMemorySubtract                    = 0xD4
    KeypadMemoryMultiply                    = 0xD5
    KeypadMemoryDivide                      = 0xD6
    Keypad_Plus_or_Minus                    = 0xD7 # + / -
    KeypadClear                             = 0xD8
    KeypadClearEntry                        = 0xD9
    KeypadBinary                            = 0xDA
    KeypadOctal                             = 0xDB
    KeypadDecimal                           = 0xDC
    KeypadHexadecimal                       = 0xDD
    __Reserved1_Begin                       = 0xDE
    __Reserved1_End                         = 0xDF
    KeyboardLeftContrl                      = 0xE0 # 左Ctrl
    KeyboardLeftShift                       = 0xE1 # 左Shift
    KeyboardLeftAlt                         = 0xE2 # 左Alt
    KeyboardLeftGUI                         = 0xE3 # 左GUI是啥
    KeyboardRightContrl                     = 0xE4 # 右Ctrl
    KeyboardRightShift                      = 0xE5 # 右Shift
    KeyboardRightAlt                        = 0xE6 # 右Alt
    KeyboardRightGUI                        = 0xE7
    __Reserved2_Begin                       = 0xE8
    __Reserved2_End                         = 0xFFFF

    def to_bytes(self):
        length = 0
        if(self.bit_length() <= 8):
            length = 1
        elif(self.bit_length() <= 16):
            length = 2
        elif(self.bit_length() <= 32):
            length = 4
        return super().to_bytes(length=length, byteorder='little', signed=False)

KeypadPage = KeyboardPage

