from .GenericDesktopPage import *
from .SimulationControlsPage import *
from .VRControlsPage import *
from .SportControlsPage import *
from .GameControlsPage import *
from .GenericDeviceControlsPage import *
from .KeyboardPage import *
from .LEDPage import *
from .ButtonPage import *
from .OrdinalPage import *
from .TelephonyDevicePage import *
from .ConsumerPage import *
from .DigitizersPage import *
from .HapticsPage import *
from .PhysicalInputDevicePage import *
# from .UnicodePage import *
from .SoCPage import *
from .EyeandHeadTrackersPage import *
from .AuxiliaryDisplayPage import *
from .SensorsPage import *
from .MedicalInstrumentPage import *
from .BrailleDisplayPage import *
from .LightingAndIlluminationPage import *
from .MonitorPage import *
from .MonitorEnumeratedPage import *
from .VESAVirtualControlsPage import *
from .PowerPage import *
from .BatterySystemPage import *
from .BarcodeScannerPage import *
from .ScalesPage import *
from .MagneticStripeReaderPage import *
from .CameraControlPage import *
from .ArcadePage import *
# from .GamingDevicePage import *
from .FIDOAlliancePage import *